[email_credentials]
email_address = "bemfamily7@gmail.com"
email_password = "NetaTomasUnguita"

[database]
url = "postgresql://neondb_owner:npg_6cNemLyCvbE8@ep-billowing-sound-ad0pjs2s-pooler.c-2.us-east-1.aws.neon.tech/casp.db?sslmode=require&channel_binding=require"